INSERT INTO currencies (iso_code, name) VALUES ('AED', 'UAE Dirham');
INSERT INTO currencies (iso_code, name) VALUES ('AFN', 'Afghani');
INSERT INTO currencies (iso_code, name) VALUES ('ALL', 'Lek');
INSERT INTO currencies (iso_code, name) VALUES ('AMD', 'Armenian Dram');
INSERT INTO currencies (iso_code, name) VALUES ('ANG', 'Netherlands Antillean Guilder');
INSERT INTO currencies (iso_code, name) VALUES ('AOA', 'Kwanza');
INSERT INTO currencies (iso_code, name) VALUES ('ARS', 'Argentine Peso');
INSERT INTO currencies (iso_code, name) VALUES ('AUD', 'Australian Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('AWG', 'Aruban Florin');
INSERT INTO currencies (iso_code, name) VALUES ('AZN', 'Azerbaijanian Manat');
INSERT INTO currencies (iso_code, name) VALUES ('BAM', 'Convertible Mark');
INSERT INTO currencies (iso_code, name) VALUES ('BBD', 'Barbados Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('BDT', 'Taka');
INSERT INTO currencies (iso_code, name) VALUES ('BGN', 'Bulgarian Lev');
INSERT INTO currencies (iso_code, name) VALUES ('BHD', 'Bahraini Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('BIF', 'Burundi Franc');
INSERT INTO currencies (iso_code, name) VALUES ('BMD', 'Bermudian Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('BND', 'Brunei Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('BOB', 'Boliviano');
INSERT INTO currencies (iso_code, name) VALUES ('BRL', 'Brazilian Real');
INSERT INTO currencies (iso_code, name) VALUES ('BSD', 'Bahamian Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('BTN', 'Ngultrum');
INSERT INTO currencies (iso_code, name) VALUES ('BWP', 'Pula');
INSERT INTO currencies (iso_code, name) VALUES ('BYN', 'Belarussian Ruble');
INSERT INTO currencies (iso_code, name) VALUES ('BZD', 'Belize Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('CAD', 'Canadian Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('CDF', 'Congolese Franc');
INSERT INTO currencies (iso_code, name) VALUES ('CHF', 'Swiss Franc');
INSERT INTO currencies (iso_code, name) VALUES ('CLP', 'Chilean Peso');
INSERT INTO currencies (iso_code, name) VALUES ('CNY', 'Yuan Renminbi');
INSERT INTO currencies (iso_code, name) VALUES ('COP', 'Colombian Peso');
INSERT INTO currencies (iso_code, name) VALUES ('CRC', 'Costa Rican Colon');
INSERT INTO currencies (iso_code, name) VALUES ('CUP', 'Cuban Peso');
INSERT INTO currencies (iso_code, name) VALUES ('CVE', 'Cabo Verde Escudo');
INSERT INTO currencies (iso_code, name) VALUES ('CZK', 'Czech Koruna');
INSERT INTO currencies (iso_code, name) VALUES ('DJF', 'Djibouti Franc');
INSERT INTO currencies (iso_code, name) VALUES ('DKK', 'Danish Krone');
INSERT INTO currencies (iso_code, name) VALUES ('DOP', 'Dominican Peso');
INSERT INTO currencies (iso_code, name) VALUES ('DZD', 'Algerian Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('EGP', 'Egyptian Pound');
INSERT INTO currencies (iso_code, name) VALUES ('ERN', 'Nakfa');
INSERT INTO currencies (iso_code, name) VALUES ('ETB', 'Ethiopian Birr');
INSERT INTO currencies (iso_code, name) VALUES ('EUR', 'Euro');
INSERT INTO currencies (iso_code, name) VALUES ('FJD', 'Fiji Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('GBP', 'Pound Sterling');
INSERT INTO currencies (iso_code, name) VALUES ('GEL', 'Lari');
INSERT INTO currencies (iso_code, name) VALUES ('GHS', 'Ghana Cedi');
INSERT INTO currencies (iso_code, name) VALUES ('GIP', 'Gibraltar Pound');
INSERT INTO currencies (iso_code, name) VALUES ('GMD', 'Dalasi');
INSERT INTO currencies (iso_code, name) VALUES ('GNF', 'Guinea Franc');
INSERT INTO currencies (iso_code, name) VALUES ('GTQ', 'Quetzal');
INSERT INTO currencies (iso_code, name) VALUES ('GYD', 'Guyana Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('HKD', 'Hong Kong Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('HNL', 'Lempira');
INSERT INTO currencies (iso_code, name) VALUES ('HRK', 'Kuna');
INSERT INTO currencies (iso_code, name) VALUES ('HTG', 'Gourde');
INSERT INTO currencies (iso_code, name) VALUES ('HUF', 'Forint');
INSERT INTO currencies (iso_code, name) VALUES ('IDR', 'Rupiah');
INSERT INTO currencies (iso_code, name) VALUES ('ILS', 'New Israeli Sheqel');
INSERT INTO currencies (iso_code, name) VALUES ('INR', 'Indian Rupee');
INSERT INTO currencies (iso_code, name) VALUES ('IQD', 'Iraqi Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('IRR', 'Iranian Rial');
INSERT INTO currencies (iso_code, name) VALUES ('ISK', 'Iceland Krona');
INSERT INTO currencies (iso_code, name) VALUES ('JMD', 'Jamaican Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('JOD', 'Jordanian Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('JPY', 'Yen');
INSERT INTO currencies (iso_code, name) VALUES ('KES', 'Kenyan Shilling');
INSERT INTO currencies (iso_code, name) VALUES ('KGS', 'Som');
INSERT INTO currencies (iso_code, name) VALUES ('KHR', 'Riel');
INSERT INTO currencies (iso_code, name) VALUES ('KMF', 'Comoro Franc');
INSERT INTO currencies (iso_code, name) VALUES ('KPW', 'North Korean Won');
INSERT INTO currencies (iso_code, name) VALUES ('KRW', 'Won');
INSERT INTO currencies (iso_code, name) VALUES ('KWD', 'Kuwaiti Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('KYD', 'Cayman Islands Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('KZT', 'Tenge');
INSERT INTO currencies (iso_code, name) VALUES ('LAK', 'Kip');
INSERT INTO currencies (iso_code, name) VALUES ('LBP', 'Lebanese Pound');
INSERT INTO currencies (iso_code, name) VALUES ('LKR', 'Sri Lanka Rupee');
INSERT INTO currencies (iso_code, name) VALUES ('LRD', 'Liberian Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('LSL', 'Loti');
INSERT INTO currencies (iso_code, name) VALUES ('LYD', 'Libyan Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('MAD', 'Moroccan Dirham');
INSERT INTO currencies (iso_code, name) VALUES ('MDL', 'Moldovan Leu');
INSERT INTO currencies (iso_code, name) VALUES ('MGA', 'Malagasy Ariary');
INSERT INTO currencies (iso_code, name) VALUES ('MKD', 'Denar');
INSERT INTO currencies (iso_code, name) VALUES ('MMK', 'Kyat');
INSERT INTO currencies (iso_code, name) VALUES ('MNT', 'Tugrik');
INSERT INTO currencies (iso_code, name) VALUES ('MOP', 'Pataca');
INSERT INTO currencies (iso_code, name) VALUES ('MRU', 'Ouguiya');
INSERT INTO currencies (iso_code, name) VALUES ('MUR', 'Mauritius Rupee');
INSERT INTO currencies (iso_code, name) VALUES ('MVR', 'Rufiyaa');
INSERT INTO currencies (iso_code, name) VALUES ('MWK', 'Kwacha');
INSERT INTO currencies (iso_code, name) VALUES ('MXN', 'Mexican Peso');
INSERT INTO currencies (iso_code, name) VALUES ('MYR', 'Malaysian Ringgit');
INSERT INTO currencies (iso_code, name) VALUES ('MZN', 'Mozambique Metical');
INSERT INTO currencies (iso_code, name) VALUES ('NAD', 'Namibia Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('NGN', 'Naira');
INSERT INTO currencies (iso_code, name) VALUES ('NIO', 'Cordoba Oro');
INSERT INTO currencies (iso_code, name) VALUES ('NOK', 'Norwegian Krone');
INSERT INTO currencies (iso_code, name) VALUES ('NPR', 'Nepalese Rupee');
INSERT INTO currencies (iso_code, name) VALUES ('NZD', 'New Zealand Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('OMR', 'Rial Omani');
INSERT INTO currencies (iso_code, name) VALUES ('PAB', 'Balboa');
INSERT INTO currencies (iso_code, name) VALUES ('PEN', 'Nuevo Sol');
INSERT INTO currencies (iso_code, name) VALUES ('PGK', 'Kina');
INSERT INTO currencies (iso_code, name) VALUES ('PHP', 'Philippine Peso');
INSERT INTO currencies (iso_code, name) VALUES ('PKR', 'Pakistan Rupee');
INSERT INTO currencies (iso_code, name) VALUES ('PLN', 'Zloty');
INSERT INTO currencies (iso_code, name) VALUES ('PYG', 'Guarani');
INSERT INTO currencies (iso_code, name) VALUES ('QAR', 'Qatari Rial');
INSERT INTO currencies (iso_code, name) VALUES ('RON', 'Romanian Leu');
INSERT INTO currencies (iso_code, name) VALUES ('RSD', 'Serbian Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('RUB', 'Russian Ruble');
INSERT INTO currencies (iso_code, name) VALUES ('RWF', 'Rwanda Franc');
INSERT INTO currencies (iso_code, name) VALUES ('SAR', 'Saudi Riyal');
INSERT INTO currencies (iso_code, name) VALUES ('SBD', 'Solomon Islands Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('SCR', 'Seychelles Rupee');
INSERT INTO currencies (iso_code, name) VALUES ('SDG', 'Sudanese Pound');
INSERT INTO currencies (iso_code, name) VALUES ('SEK', 'Swedish Krona');
INSERT INTO currencies (iso_code, name) VALUES ('SGD', 'Singapore Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('SLE', 'Leone');
INSERT INTO currencies (iso_code, name) VALUES ('SOS', 'Somali Shilling');
INSERT INTO currencies (iso_code, name) VALUES ('SRD', 'Surinam Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('SSP', 'South Sudanese Pound');
INSERT INTO currencies (iso_code, name) VALUES ('STN', 'Dobra');
INSERT INTO currencies (iso_code, name) VALUES ('SVC', 'El Salvador Colon');
INSERT INTO currencies (iso_code, name) VALUES ('SYP', 'Syrian Pound');
INSERT INTO currencies (iso_code, name) VALUES ('SZL', 'Lilangeni');
INSERT INTO currencies (iso_code, name) VALUES ('THB', 'Baht');
INSERT INTO currencies (iso_code, name) VALUES ('TJS', 'Somoni');
INSERT INTO currencies (iso_code, name) VALUES ('TMT', 'Turkmenistan New Manat');
INSERT INTO currencies (iso_code, name) VALUES ('TND', 'Tunisian Dinar');
INSERT INTO currencies (iso_code, name) VALUES ('TOP', 'Pa''anga');
INSERT INTO currencies (iso_code, name) VALUES ('TRY', 'Turkish Lira');
INSERT INTO currencies (iso_code, name) VALUES ('TTD', 'Trinidad and Tobago Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('TWD', 'New Taiwan Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('TZS', 'Tanzanian Shilling');
INSERT INTO currencies (iso_code, name) VALUES ('UAH', 'Hryvnia');
INSERT INTO currencies (iso_code, name) VALUES ('UGX', 'Uganda Shilling');
INSERT INTO currencies (iso_code, name) VALUES ('USD', 'US Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('UYU', 'Peso Uruguayo');
INSERT INTO currencies (iso_code, name) VALUES ('UZS', 'Uzbekistan Sum');
INSERT INTO currencies (iso_code, name) VALUES ('VEF', 'Bolivar');
INSERT INTO currencies (iso_code, name) VALUES ('VND', 'Dong');
INSERT INTO currencies (iso_code, name) VALUES ('VUV', 'Vatu');
INSERT INTO currencies (iso_code, name) VALUES ('WST', 'Tala');
INSERT INTO currencies (iso_code, name) VALUES ('XAF', 'CFA Franc BEAC');
INSERT INTO currencies (iso_code, name) VALUES ('XCD', 'East Caribbean Dollar');
INSERT INTO currencies (iso_code, name) VALUES ('XOF', 'CFA Franc BCEAO');
INSERT INTO currencies (iso_code, name) VALUES ('XPF', 'CFP Franc');
INSERT INTO currencies (iso_code, name) VALUES ('YER', 'Yemeni Rial');
INSERT INTO currencies (iso_code, name) VALUES ('ZAR', 'Rand');
INSERT INTO currencies (iso_code, name) VALUES ('ZMW', 'Zambian Kwacha');
INSERT INTO currencies (iso_code, name) VALUES ('ZWL', 'Zimbabwe Dollar');