INSERT INTO order_statuses(name) VALUES ('Created');
INSERT INTO order_statuses(name) VALUES ('Dispatched to Specialist');
INSERT INTO order_statuses(name) VALUES ('Specialist Assessing');
INSERT INTO order_statuses(name) VALUES ('Price Adjustment Requested');
INSERT INTO order_statuses(name) VALUES ('Price Adjustment Approved');
INSERT INTO order_statuses(name) VALUES ('Price Adjustment Rejected');
INSERT INTO order_statuses(name) VALUES ('Specialist Repairing');
INSERT INTO order_statuses(name) VALUES ('Dispatched to Customer');
INSERT INTO order_statuses(name) VALUES ('Received by Customer');
INSERT INTO order_statuses(name) VALUES ('Payment requested');
INSERT INTO order_statuses(name) VALUES ('Payment received');
INSERT INTO order_statuses(name) VALUES ('Closed');
INSERT INTO order_statuses(name) VALUES ('Cancelled');