INSERT INTO products (category, subcategory) VALUES ('Arts, Crafts & Sewing', 'Printing Presses & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Arts, Crafts & Sewing', 'Sewing Machines');
INSERT INTO products (category, subcategory) VALUES ('Arts, Crafts & Sewing', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Audio Headphones & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Blu-ray Players & Recorders');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Cassette Players & Recorders');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'CB & Two-Way Radios');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'CD Players');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Compact Radios & Stereos');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Digital Voice Recorders');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'DVD Players & Recorders');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Home Theater Systems');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'MP3 & MP4 Players');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Radios');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Satellite Television Products');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Speakers & Audio Systems');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Streaming Media Players');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Televisions');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Turntables & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'TV-DVD Combinations');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'VCRs');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Video Projectors');
INSERT INTO products (category, subcategory) VALUES ('Audio-Visual', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Beauty & Personal Care', 'Personal Care Products');
INSERT INTO products (category, subcategory) VALUES ('Beauty & Personal Care', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Camera & Photo Accessories');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Digital Cameras');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Film Cameras');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Photo Printers & Scanners');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Quadcopters & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Video Cameras');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Video Surveillance Equipment');
INSERT INTO products (category, subcategory) VALUES ('Camera & Photo', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Cell Phones & Accessories', 'Cell Phone Accessories');
INSERT INTO products (category, subcategory) VALUES ('Cell Phones & Accessories', 'Cell Phones');
INSERT INTO products (category, subcategory) VALUES ('Cell Phones & Accessories', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Computer Audio Devices');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Computer Game Hardware');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Computer Keyboards, Mice & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Computer Monitors');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Computer Servers');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Computer Tablets');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Data Storage');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Desktop Computers');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Laptop Computers');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'USB Gadgets');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Webcams');
INSERT INTO products (category, subcategory) VALUES ('Computers & Accessories', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('eBook Readers & Accessories', 'eBook Readers');
INSERT INTO products (category, subcategory) VALUES ('eBook Readers & Accessories', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Dehumidifiers');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Home Air Purifiers');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Household Fans');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Humidifiers');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Indoor Space Heaters');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Room Air Conditioners');
INSERT INTO products (category, subcategory) VALUES ('Heating, Cooling & Air Quality', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Dishwashers');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Doorbells');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Electric Cookers');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Home Automation Devices');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Ironing Products');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Laundry Appliances');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Refrigerators, Freezers & Ice Makers');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Room Air Conditioners & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Safety & Security Devices');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Vacuum Cleaners & Steam Cleaners');
INSERT INTO products (category, subcategory) VALUES ('Home Electronics', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', '3D Printers');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', '3D Scanners');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Cutting Tools');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Digital Signage Equipment');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Electronic Components');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Filtration');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Food Service Equipment & Supplies');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Hydraulics, Pneumatics & Plumbing');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Industrial Power & Hand Tools');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Lab Instruments & Equipment');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Occupational Health & Safety Products');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Security & Surveillance Equipment');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Testing, Measurement & Inspection Devices');
INSERT INTO products (category, subcategory) VALUES ('Industrial & Scientific', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Kitchen Appliances', 'Coffee, Tea & Espresso');
INSERT INTO products (category, subcategory) VALUES ('Kitchen Appliances', 'Electric Knives');
INSERT INTO products (category, subcategory) VALUES ('Kitchen Appliances', 'Kitchen Small Appliances');
INSERT INTO products (category, subcategory) VALUES ('Kitchen Appliances', 'Kitchen Utensils & Gadgets');
INSERT INTO products (category, subcategory) VALUES ('Kitchen Appliances', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Electronic Drums');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Electronic Music, DJ & Karaoke');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Music Recording Equipment');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Musical Instrument Accessories');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Musical Instrument Amplifiers & Effects');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Musical Instrument Keyboards & MIDI');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Recording Microphones & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Stage & Sound Equipment');
INSERT INTO products (category, subcategory) VALUES ('Musical Instruments', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Office Electronics', 'Fax Machines');
INSERT INTO products (category, subcategory) VALUES ('Office Electronics', 'Point-of-Sale (POS) Equipment');
INSERT INTO products (category, subcategory) VALUES ('Office Electronics', 'Printers, Scanners, Copiers');
INSERT INTO products (category, subcategory) VALUES ('Office Electronics', 'Telephones');
INSERT INTO products (category, subcategory) VALUES ('Office Electronics', 'Video Projectors & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Office Electronics', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Patio, Lawn & Garden', 'Outdoor Kitchen Appliances');
INSERT INTO products (category, subcategory) VALUES ('Patio, Lawn & Garden', 'Outdoor Power & Lawn Equipment');
INSERT INTO products (category, subcategory) VALUES ('Patio, Lawn & Garden', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Robotics', 'Unmanned Aerial Vehicles (UAVs)');
INSERT INTO products (category, subcategory) VALUES ('Robotics', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Camping & Hiking Equipment');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Cycling Equipment');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Exercise & Fitness Equipment');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Golf Accessories');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Hunting & Fishing');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Leisure & Games Equipment');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Other Sports Types');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Outdoor Recreation Accessories');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Sports Accessories');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Team Sports Equipment');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Water Sports');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Winter Sports Equipment');
INSERT INTO products (category, subcategory) VALUES ('Sports & Outdoors', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Tools', 'Electrical Tools & Hardware');
INSERT INTO products (category, subcategory) VALUES ('Tools', 'Power Tools');
INSERT INTO products (category, subcategory) VALUES ('Tools', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Toys & Games', 'Electronic Toys');
INSERT INTO products (category, subcategory) VALUES ('Toys & Games', 'Remote & App Controlled Vehicles & Parts');
INSERT INTO products (category, subcategory) VALUES ('Toys & Games', 'Video Game Consoles & Accessories');
INSERT INTO products (category, subcategory) VALUES ('Toys & Games', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Vehicle Electronics', 'Car Audio & Video Accessories');
INSERT INTO products (category, subcategory) VALUES ('Vehicle Electronics', 'Car Electronics');
INSERT INTO products (category, subcategory) VALUES ('Vehicle Electronics', 'Marine Electronics');
INSERT INTO products (category, subcategory) VALUES ('Vehicle Electronics', 'Vehicle GPS Units & Equipment');
INSERT INTO products (category, subcategory) VALUES ('Vehicle Electronics', 'Other-Misc.');
INSERT INTO products (category, subcategory) VALUES ('Wearable Technology', 'Smart Glasses');
INSERT INTO products (category, subcategory) VALUES ('Wearable Technology', 'Smartwatches & Smart Rings');
INSERT INTO products (category, subcategory) VALUES ('Wearable Technology', 'Other-Misc.');