<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('currencies', function (Blueprint $table) {
            $table->id();
            $table->string('iso_code', 3)->unique();
            $table->string('name', 255);
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();
            $table->timestamp('deleted_at')->nullable();
        });

        DB::table('currencies')->insert([
            ['iso_code' => 'AED', 'name' => 'UAE Dirham'],
            ['iso_code' => 'AFN', 'name' => 'Afghani'],
            ['iso_code' => 'ALL', 'name' => 'Lek'],
            ['iso_code' => 'AMD', 'name' => 'Armenian Dram'],
            ['iso_code' => 'ANG', 'name' => 'Netherlands Antillean Guilder'],
            ['iso_code' => 'AOA', 'name' => 'Kwanza'],
            ['iso_code' => 'ARS', 'name' => 'Argentine Peso'],
            ['iso_code' => 'AUD', 'name' => 'Australian Dollar'],
            ['iso_code' => 'AWG', 'name' => 'Aruban Florin'],
            ['iso_code' => 'AZN', 'name' => 'Azerbaijanian Manat'],
            ['iso_code' => 'BAM', 'name' => 'Convertible Mark'],
            ['iso_code' => 'BBD', 'name' => 'Barbados Dollar'],
            ['iso_code' => 'BDT', 'name' => 'Taka'],
            ['iso_code' => 'BGN', 'name' => 'Bulgarian Lev'],
            ['iso_code' => 'BHD', 'name' => 'Bahraini Dinar'],
            ['iso_code' => 'BIF', 'name' => 'Burundi Franc'],
            ['iso_code' => 'BMD', 'name' => 'Bermudian Dollar'],
            ['iso_code' => 'BND', 'name' => 'Brunei Dollar'],
            ['iso_code' => 'BOB', 'name' => 'Boliviano'],
            ['iso_code' => 'BRL', 'name' => 'Brazilian Real'],
            ['iso_code' => 'BSD', 'name' => 'Bahamian Dollar'],
            ['iso_code' => 'BTN', 'name' => 'Ngultrum'],
            ['iso_code' => 'BWP', 'name' => 'Pula'],
            ['iso_code' => 'BYN', 'name' => 'Belarussian Ruble'],
            ['iso_code' => 'BZD', 'name' => 'Belize Dollar'],
            ['iso_code' => 'CAD', 'name' => 'Canadian Dollar'],
            ['iso_code' => 'CDF', 'name' => 'Congolese Franc'],
            ['iso_code' => 'CHF', 'name' => 'Swiss Franc'],
            ['iso_code' => 'CLP', 'name' => 'Chilean Peso'],
            ['iso_code' => 'CNY', 'name' => 'Yuan Renminbi'],
            ['iso_code' => 'COP', 'name' => 'Colombian Peso'],
            ['iso_code' => 'CRC', 'name' => 'Costa Rican Colon'],
            ['iso_code' => 'CUP', 'name' => 'Cuban Peso'],
            ['iso_code' => 'CVE', 'name' => 'Cabo Verde Escudo'],
            ['iso_code' => 'CZK', 'name' => 'Czech Koruna'],
            ['iso_code' => 'DJF', 'name' => 'Djibouti Franc'],
            ['iso_code' => 'DKK', 'name' => 'Danish Krone'],
            ['iso_code' => 'DOP', 'name' => 'Dominican Peso'],
            ['iso_code' => 'DZD', 'name' => 'Algerian Dinar'],
            ['iso_code' => 'EGP', 'name' => 'Egyptian Pound'],
            ['iso_code' => 'ERN', 'name' => 'Nakfa'],
            ['iso_code' => 'ETB', 'name' => 'Ethiopian Birr'],
            ['iso_code' => 'EUR', 'name' => 'Euro'],
            ['iso_code' => 'FJD', 'name' => 'Fiji Dollar'],
            ['iso_code' => 'GBP', 'name' => 'Pound Sterling'],
            ['iso_code' => 'GEL', 'name' => 'Lari'],
            ['iso_code' => 'GHS', 'name' => 'Ghana Cedi'],
            ['iso_code' => 'GIP', 'name' => 'Gibraltar Pound'],
            ['iso_code' => 'GMD', 'name' => 'Dalasi'],
            ['iso_code' => 'GNF', 'name' => 'Guinea Franc'],
            ['iso_code' => 'GTQ', 'name' => 'Quetzal'],
            ['iso_code' => 'GYD', 'name' => 'Guyana Dollar'],
            ['iso_code' => 'HKD', 'name' => 'Hong Kong Dollar'],
            ['iso_code' => 'HNL', 'name' => 'Lempira'],
            ['iso_code' => 'HRK', 'name' => 'Kuna'],
            ['iso_code' => 'HTG', 'name' => 'Gourde'],
            ['iso_code' => 'HUF', 'name' => 'Forint'],
            ['iso_code' => 'IDR', 'name' => 'Rupiah'],
            ['iso_code' => 'ILS', 'name' => 'New Israeli Sheqel'],
            ['iso_code' => 'INR', 'name' => 'Indian Rupee'],
            ['iso_code' => 'IQD', 'name' => 'Iraqi Dinar'],
            ['iso_code' => 'IRR', 'name' => 'Iranian Rial'],
            ['iso_code' => 'ISK', 'name' => 'Iceland Krona'],
            ['iso_code' => 'JMD', 'name' => 'Jamaican Dollar'],
            ['iso_code' => 'JOD', 'name' => 'Jordanian Dinar'],
            ['iso_code' => 'JPY', 'name' => 'Yen'],
            ['iso_code' => 'KES', 'name' => 'Kenyan Shilling'],
            ['iso_code' => 'KGS', 'name' => 'Som'],
            ['iso_code' => 'KHR', 'name' => 'Riel'],
            ['iso_code' => 'KMF', 'name' => 'Comoro Franc'],
            ['iso_code' => 'KPW', 'name' => 'North Korean Won'],
            ['iso_code' => 'KRW', 'name' => 'Won'],
            ['iso_code' => 'KWD', 'name' => 'Kuwaiti Dinar'],
            ['iso_code' => 'KYD', 'name' => 'Cayman Islands Dollar'],
            ['iso_code' => 'KZT', 'name' => 'Tenge'],
            ['iso_code' => 'LAK', 'name' => 'Kip'],
            ['iso_code' => 'LBP', 'name' => 'Lebanese Pound'],
            ['iso_code' => 'LKR', 'name' => 'Sri Lanka Rupee'],
            ['iso_code' => 'LRD', 'name' => 'Liberian Dollar'],
            ['iso_code' => 'LSL', 'name' => 'Loti'],
            ['iso_code' => 'LYD', 'name' => 'Libyan Dinar'],
            ['iso_code' => 'MAD', 'name' => 'Moroccan Dirham'],
            ['iso_code' => 'MDL', 'name' => 'Moldovan Leu'],
            ['iso_code' => 'MGA', 'name' => 'Malagasy Ariary'],
            ['iso_code' => 'MKD', 'name' => 'Denar'],
            ['iso_code' => 'MMK', 'name' => 'Kyat'],
            ['iso_code' => 'MNT', 'name' => 'Tugrik'],
            ['iso_code' => 'MOP', 'name' => 'Pataca'],
            ['iso_code' => 'MRU', 'name' => 'Ouguiya'],
            ['iso_code' => 'MUR', 'name' => 'Mauritius Rupee'],
            ['iso_code' => 'MVR', 'name' => 'Rufiyaa'],
            ['iso_code' => 'MWK', 'name' => 'Kwacha'],
            ['iso_code' => 'MXN', 'name' => 'Mexican Peso'],
            ['iso_code' => 'MYR', 'name' => 'Malaysian Ringgit'],
            ['iso_code' => 'MZN', 'name' => 'Mozambique Metical'],
            ['iso_code' => 'NAD', 'name' => 'Namibia Dollar'],
            ['iso_code' => 'NGN', 'name' => 'Naira'],
            ['iso_code' => 'NIO', 'name' => 'Cordoba Oro'],
            ['iso_code' => 'NOK', 'name' => 'Norwegian Krone'],
            ['iso_code' => 'NPR', 'name' => 'Nepalese Rupee'],
            ['iso_code' => 'NZD', 'name' => 'New Zealand Dollar'],
            ['iso_code' => 'OMR', 'name' => 'Rial Omani'],
            ['iso_code' => 'PAB', 'name' => 'Balboa'],
            ['iso_code' => 'PEN', 'name' => 'Nuevo Sol'],
            ['iso_code' => 'PGK', 'name' => 'Kina'],
            ['iso_code' => 'PHP', 'name' => 'Philippine Peso'],
            ['iso_code' => 'PKR', 'name' => 'Pakistan Rupee'],
            ['iso_code' => 'PLN', 'name' => 'Zloty'],
            ['iso_code' => 'PYG', 'name' => 'Guarani'],
            ['iso_code' => 'QAR', 'name' => 'Qatari Rial'],
            ['iso_code' => 'RON', 'name' => 'Romanian Leu'],
            ['iso_code' => 'RSD', 'name' => 'Serbian Dinar'],
            ['iso_code' => 'RUB', 'name' => 'Russian Ruble'],
            ['iso_code' => 'RWF', 'name' => 'Rwanda Franc'],
            ['iso_code' => 'SAR', 'name' => 'Saudi Riyal'],
            ['iso_code' => 'SBD', 'name' => 'Solomon Islands Dollar'],
            ['iso_code' => 'SCR', 'name' => 'Seychelles Rupee'],
            ['iso_code' => 'SDG', 'name' => 'Sudanese Pound'],
            ['iso_code' => 'SEK', 'name' => 'Swedish Krona'],
            ['iso_code' => 'SGD', 'name' => 'Singapore Dollar'],
            ['iso_code' => 'SLE', 'name' => 'Leone'],
            ['iso_code' => 'SOS', 'name' => 'Somali Shilling'],
            ['iso_code' => 'SRD', 'name' => 'Surinam Dollar'],
            ['iso_code' => 'SSP', 'name' => 'South Sudanese Pound'],
            ['iso_code' => 'STN', 'name' => 'Dobra'],
            ['iso_code' => 'SVC', 'name' => 'El Salvador Colon'],
            ['iso_code' => 'SYP', 'name' => 'Syrian Pound'],
            ['iso_code' => 'SZL', 'name' => 'Lilangeni'],
            ['iso_code' => 'THB', 'name' => 'Baht'],
            ['iso_code' => 'TJS', 'name' => 'Somoni'],
            ['iso_code' => 'TMT', 'name' => 'Turkmenistan New Manat'],
            ['iso_code' => 'TND', 'name' => 'Tunisian Dinar'],
            ['iso_code' => 'TOP', 'name' => 'Pa\'anga'],
            ['iso_code' => 'TRY', 'name' => 'Turkish Lira'],
            ['iso_code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar'],
            ['iso_code' => 'TWD', 'name' => 'New Taiwan Dollar'],
            ['iso_code' => 'TZS', 'name' => 'Tanzanian Shilling'],
            ['iso_code' => 'UAH', 'name' => 'Hryvnia'],
            ['iso_code' => 'UGX', 'name' => 'Uganda Shilling'],
            ['iso_code' => 'USD', 'name' => 'US Dollar'],
            ['iso_code' => 'UYU', 'name' => 'Peso Uruguayo'],
            ['iso_code' => 'UZS', 'name' => 'Uzbekistan Sum'],
            ['iso_code' => 'VEF', 'name' => 'Bolivar'],
            ['iso_code' => 'VND', 'name' => 'Dong'],
            ['iso_code' => 'VUV', 'name' => 'Vatu'],
            ['iso_code' => 'WST', 'name' => 'Tala'],
            ['iso_code' => 'XAF', 'name' => 'CFA Franc BEAC'],
            ['iso_code' => 'XCD', 'name' => 'East Caribbean Dollar'],
            ['iso_code' => 'XOF', 'name' => 'CFA Franc BCEAO'],
            ['iso_code' => 'XPF', 'name' => 'CFP Franc'],
            ['iso_code' => 'YER', 'name' => 'Yemeni Rial'],
            ['iso_code' => 'ZAR', 'name' => 'Rand'],
            ['iso_code' => 'ZMW', 'name' => 'Zambian Kwacha'],
            ['iso_code' => 'ZWL', 'name' => 'Zimbabwe Dollar'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('currencies');
    }
};
